### ISSUE TITLE
We need to create a web interface that will generate a json for users

### ISSUE THREAD

**Issue by bennytehcat** [The-GNTL-Project/Mining-Pools#8]
Should take four bits of info, coin, wallet, "Worker Name" and email. 

It should ask three questions:

Do you want to mine CPU, GPU (AMD), GPU (NVidia), and we set those true/false.

Edit: For the record, Giggidy states, "I'm taking partial credit for this amazing idea we had total together"

**Comment by BKdilse** [comment]
no further development on this.
