### ISSUE TITLE
Shold we simplify xmrig download procedure into a single zip (cpu+amd+nvidia), and host the file on https to avoid filesize limitations?

### ISSUE THREAD

**Issue by bennytehcat** [The-GNTL-Project/Mining-Pools#9]
If we go to a single zip, we can eliminate a support step of asking if you need nVidia.  No one is going to have a computer lockup because they downloaded a few extra MB of dll files.  If we host the file on https://gntl.cash, we can keep an archive of previous versions, and BK would only need to update the download link in #tools-configs-scripts.

**Comment by BKdilse** [comment]
Not a good idea to make a 0 fee version public, as this is not fair for the devs.  Its only available to our miners.

**Comment by bennytehcat** [comment]
What if we didn't make a forward version, can keep it hidden and only link from discord?

**Comment by BKdilse** [comment]
That's an option.  But... bundling nvidia in when someone is mining a CPU coin is pointless, hence the current separation.  We need to see what the demand for this is.

**Comment by BKdilse** [comment]
The other issue is the latest version of Cuda does not work with all GPUs, as we have found.

**Comment by BKdilse** [comment]
As discussed, this is not an option.
